[package]
name = "rain-math-float-macro"
edition.workspace = true
version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
description = "Compile-time and fallible literal macros for rain-math-float"

[lib]
proc-macro = true

[dependencies]
rain-math-float.workspace = true

[dev-dependencies]
alloy-primitives.workspace = true
rain-math-float.workspace = true
trybuild.workspace = true
