version = 1

[[annotations]]
path = [
    ".envrc",
    ".gas-snapshot",
    ".github/workflows/**/",
    ".vscode/**/",
    "Cargo.lock",
    "Cargo.toml",
    ".gitignore",
    ".gitmodules",
    "package-lock.json",
    "package.json",
    "scripts/**/",
    "test_js/**/",
    "tsconfig.json",
    "README.md",
    "crates/**/",
    "flake.lock",
    "flake.nix",
    "foundry.toml",
    "slither.config.json",
    "REUSE.toml"
]
SPDX-FileCopyrightText = "Copyright (c) 2020 Rain Open Source Software Ltd"
SPDX-License-Identifier = "LicenseRef-DCL-1.0"
